project:
  type: website
  output-dir: docs

website:
  title: "Julia Tutorials for BEFW"
  page-navigation: true
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Setting Up"
        contents:
          - index.qmd
          - 01_download_setup.qmd
      - section: "Basic Calculations and Objects"
        contents:
          - 02_maths_vector_stuff.qmd
          - 03_dataframes.qmd
      - section: "Programming, Plotting and Extra Tips"
        contents:
          - 04_programming_basics.qmd
          - 05_plotting.qmd
          - 06_tips_tricks.qmd
      - section: "Intro to Differential Equations"
        contents:
          - 07_differential_equations.qmd
      - section: "Intro to the BEFW model"
        contents:
          - 08_intro_end.qmd
          - 09_experiments_end.qmd
          - 10_complex_experiments_end.qmd
  page-footer:     
    background: primary 
    right: 
      - icon: code
        text: "{{< fa code >}} Source code"
        href: https://github.com/BecksLab/JuliaTutorials_BecksLab

format:
  html:
    theme: minty
    toc: true


execute:
  freeze: auto