project:
  type: website
  output-dir: docs

website:
  title: "Julia Tutorials for BEFWM2"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Setting Up"
        contents:
          - index.qmd
          - Tutorial-1_Downloads Setups and Your First Project.qmd
      - section: "Basic Calculations and Objects"
        contents:
          - Tutorial-2_Using Julia for Maths and Vector Stuff.qmd
          - Tutorial-3_Building and Working with DataFrames.qmd
      - section: "Programming, Plotting and Extra Tips"
        contents:
          - Tutorial-4_Programming Basics.qmd
          - Tutorial-5_Plotting in Julia.qmd
          - Tutorial-6_Extra Tips and Tricks.qmd
      - section: "Intro to Differential Equations"
        contents:
          - Tutorial-7_Intro To Differential Equations.qmd
      - section: "Intro to the BEFW model"
        contents:
          - Tutorial-8_Intro To Eco Net Dyn.qmd

format:
  html:
    theme: cosmo
    toc: true
